### GLM: Generalized Linear Model 

$y = \beta_0 + \beta_1 \times x_1 + \dots + \beta_n \times x_n  $

$S(y) = C = \frac{1}{1 + e^{-y}}$

In [18]:
import numpy as np 
from math import log

y = np.linspace(-100,100)
y

array([-100.        ,  -95.91836735,  -91.83673469,  -87.75510204,
        -83.67346939,  -79.59183673,  -75.51020408,  -71.42857143,
        -67.34693878,  -63.26530612,  -59.18367347,  -55.10204082,
        -51.02040816,  -46.93877551,  -42.85714286,  -38.7755102 ,
        -34.69387755,  -30.6122449 ,  -26.53061224,  -22.44897959,
        -18.36734694,  -14.28571429,  -10.20408163,   -6.12244898,
         -2.04081633,    2.04081633,    6.12244898,   10.20408163,
         14.28571429,   18.36734694,   22.44897959,   26.53061224,
         30.6122449 ,   34.69387755,   38.7755102 ,   42.85714286,
         46.93877551,   51.02040816,   55.10204082,   59.18367347,
         63.26530612,   67.34693878,   71.42857143,   75.51020408,
         79.59183673,   83.67346939,   87.75510204,   91.83673469,
         95.91836735,  100.        ])

In [11]:
1 / (1 + np.exp(-y))

array([3.72007598e-44, 2.20385160e-42, 1.30560825e-40, 7.73469913e-39,
       4.58219918e-37, 2.71459160e-35, 1.60818142e-33, 9.52720650e-32,
       5.64411841e-30, 3.34369499e-28, 1.98087556e-26, 1.17351253e-24,
       6.95213617e-23, 4.11859235e-21, 2.43994112e-19, 1.44547267e-17,
       8.56328550e-16, 5.07307125e-14, 3.00539459e-12, 1.78045925e-10,
       1.05478167e-08, 6.24874560e-07, 3.70175420e-05, 2.18827951e-03,
       1.14983635e-01, 8.85016365e-01, 9.97811720e-01, 9.99962982e-01,
       9.99999375e-01, 9.99999989e-01, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00])

In [22]:
-log(1/0.999   - 1)

6.906754778648465

In [23]:
-log(1/0.001 -1)

-6.906754778648554

In [34]:
class Vocabulary:
    def __init__(self):
        self.s2i = {"oov": 0}
        self.i2s = ["oov"]

    def add_word(self, word:str):
        if word in self.s2i:
            return

        self.s2i[word] = len(self.i2s)
        self.i2s.append(word)

    def __len__(self):
        return len(self.i2s)

    def get_word_id(self, word:str)->int:
        return self.s2i.get(word, 0)


vocab = Vocabulary()

def tokenizer(s:str) -> list[str]:
    return [t.lower().strip(',.') for t in s.split()]


for file_name in ["pos.txt", "neg.txt"]:
    with open(file_name) as fp:
        for line in fp:
            for token in tokenizer(line):
                vocab.add_word(token)

print(f"Vocabulary of size = {len(vocab)}")

Vocabulary of size = 446


In [35]:
dt = np.zeros((100, len(vocab)))

In [36]:
dt.shape

(100, 446)

In [39]:
doc_id = 0
for file_name in ["pos.txt", "neg.txt"]:
    with open(file_name) as fp:
        for line in fp:
            for token in tokenizer(line):
                dt[doc_id][vocab.get_word_id(token)] = 1
dt

array([[0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [50]:
c = np.array([0.99999]*50+[0.000001]*50)

In [55]:
y = -np.log( 1 / c - 1)

In [56]:
from numpy.linalg import lstsq

In [57]:
beta, *_ = lstsq(dt, y)

/tmp/ipykernel_17538/2881491656.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  beta, *_ = lstsq(dt, y)


In [63]:
1/ (1 + np.exp(-np.dot(beta, dt[0,:])))

0.99999